name: nanopim4

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/home-assistant/buildroot.git
  REPO_BRANCH: 2022.02.x-haos
  TZ: Asia/Shanghai
  UPLOAD_BIN_DIR: false

jobs:
  buildone:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      run: |
        cd buildroot
        make friendlyarm_nanopi_m4_defconfig
        make

    - name: Upload files to release
      uses: ncipollo/release-action@v1
      with:
        name: Nanopim4
        artifacts: .output/images
        allowUpdates: true
        replacesArtifacts: true  
        
        tag: ${{ env.FILE_NAME }}
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          * 这是临时文件夹 🛒
