name: nanopim4

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH Connection To Actions?'
        required: false
        default: 'false'

env:
  REPO_URL: https://github.com/home-assistant/buildroot.git
  REPO_BRANCH: 2022.02.x-haos
  TZ: Asia/Shanghai
  UPLOAD_BIN_DIR: false

jobs:
  buildone:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Setup Debug Session 'touch /tmp/keepalivegit'
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') 
      uses: csexton/debugger-action@master
    - name: Initialization environment
      run: |
        git clone -b 2022.02.x-haos https://github.com/home-assistant/buildroot.git
        cd buildroot
        make friendlyarm_nanopi_m4_defconfig
        make

    - name: Upload files to release
      uses: ncipollo/release-action@v1
      with:
        name: Nanopim4
        artifacts: /output/images/*
        allowUpdates: true
        replacesArtifacts: true  
        
        tag: Nanopim4
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          * Nanopim4
          
